apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None
  ports:
    - port:       3306
      targetPort: 3306
      protocol:   TCP
  selector:
    app: mysql
    env: production
