Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - spec/**/*.rb

Metrics/LineLength:
  Max: 120
  Exclude:
    # - config/initializers/devise.rb

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    # - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - coverage/**/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/bundle/**/*
