{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name:     {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name:     {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.deployment.mysql.image }}
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            tcpSocket:
              port: 3306
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command:
                - sh
                - -c
                - "MYSQL_PWD=\"$MYSQL_PASSWORD\" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"
          resources:
            requests:
              memory: {{ .Values.deployment.mysql.resources.memory }}
            limits:
              memory: {{ .Values.deployment.mysql.resources.memory }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap-env
            - secretRef:
                name: {{ .Chart.Name }}-secret-env
          ports:
            - containerPort: {{ .Values.deployment.mysql.port }}
              protocol:      TCP
              name:          mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name:      mysql-volume
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-persistent-volume-claim
{{- end }}
