{{- if .Values.deployment.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret-env
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
