apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  # type: LoadBalancer
  type: NodePort
  # type: ClusterIP
  # clusterIP: None
  ports:
    - port:       80
      targetPort: 80
      protocol:   TCP
  selector:
    app: app
    env: production
