apiVersion: v1
kind: Pod
metadata:
  name: app-console
  labels:
    app: app
    env: production
spec:
  containers:
    - name: console
      image: 172.16.0.30:5000/kube-sample:1.0.0
      imagePullPolicy: Always
      command:
        - "/bin/bash"
        - "-ec"
        - "trap 'exit' SIGTERM ; while :; do sleep 5 ; done"
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 256Mi
      env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key:  MYSQL_PASSWORD
      envFrom:
        - configMapRef:
            name: mysql-configmap
        - secretRef:
            name: app-secret
