apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap-puma
data:
  puma.rb: |
    threads_count = ENV.fetch('RAILS_MAX_THREADS') { 5 }
    threads threads_count, threads_count

    port       ENV.fetch('PORT') { 3000 }
    bind       'unix:///app/tmp/sockets/puma.sock'
    pidfile    '/app/tmp/pids/puma.pid'
    state_path '/app/tmp/pids/puma.state'

    environment ENV.fetch('RAILS_ENV') { 'production' }

    plugin :tmp_restart
