apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap-nginx
data:
  app.conf: |
    upstream puma {
      server unix:/nginx/sockets/puma.sock;
    }

    server {
      listen 80;
      server_name _;

      root /nginx/root;

      location /packs {
        alias        /nginx/root/packs;
        expires      max;
        add_header   Cache-Control public;
        gzip_static  on;
        gzip_proxied any;
        gzip_vary    on;
        break;
      }

      location / {
        try_files $uri @puma;
      }

      location @puma {
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host            $http_host;
        proxy_pass http://puma;
      }

      location /_status {
        access_log off;
        return 200;
      }
    }
