apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap-env-pre
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: hook-succeeded
{{- with .Values.env.configmap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
