apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret-env-pre
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-succeeded
type: Opaque
data:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
