apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: 172.16.0.30:5000/kube-sample:1.0.0
          imagePullPolicy: Always
          command:
            - bundle
            - exec
            - rake
            - db:migrate
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key:  MYSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: mysql-configmap
            - secretRef:
                name: app-secret
      restartPolicy: Never
  backoffLimit: 1
  parallelism: 1
  completions: 1
