apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SECRET_KEY_BASE: ZTNiZjc2ODJmMDViMzkyNzgwOWJhYTNkZDUzNWFlNjEzNGZkYjY2MGFhZThlZDE0OGVlZTVmMTA1MWU5ODg5MjVhOWYwOTQ0YTQ2Y2JkNDQ4M2M0NDIwNGQxYTQxMzc1MjZjMmNiMWNlNTIxNTU1ZTg5ZDhmMmFiNWYzMDdkOWI=
