apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap-nginx
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  app.conf: |
    upstream puma {
      server unix:/nginx/sockets/puma.sock;
    }

    server {
      listen 80;
      server_name _;

      set_real_ip_from  10.244.0.0/16;
      real_ip_header    X-Forwarded-For;
      # real_ip_recursive on;

      root /nginx/root;

      location /packs {
        alias        /nginx/root/packs;
        expires      max;
        add_header   Cache-Control public;
        gzip_static  on;
        gzip_proxied any;
        gzip_vary    on;
        break;
      }

      location / {
        try_files $uri @puma;
      }

      location @puma {
        proxy_read_timeout    300;
        proxy_connect_timeout 300;
        proxy_redirect        off;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_pass http://puma;
      }

      location /_status {
        access_log off;
        return 200;
      }
    }
