apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment-sidekiq
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/component:  sidekiq
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.deployment.sidekiq.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name:      {{ .Chart.Name }}
      app.kubernetes.io/instance:  {{ .Release.Name }}
      app.kubernetes.io/component: sidekiq
  template:
    metadata:
      labels:
        app.kubernetes.io/name:      {{ .Chart.Name }}
        app.kubernetes.io/instance:  {{ .Release.Name }}
        app.kubernetes.io/component: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: {{ .Values.pod.sidekiq.image }}
          imagePullPolicy: Always
          command:
            - bundle
            - exec
            - sidekiq
            - -C
            - config/sidekiq.yml
          lifecycle:
            preStop:
              exec:
                command:
                  - bundle
                  - exec
                  - sidekiqctl
                  - quiet
                  - tmp/pids/sidekiq.pid
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              path: /
              port: {{ .Values.pod.sidekiq.port }}
          resources:
            requests:
              memory: {{ .Values.pod.sidekiq.resources.memory }}
            limits:
              memory: {{ .Values.pod.sidekiq.resources.memory }}
          ports:
            - containerPort: {{ .Values.pod.sidekiq.port }}
              protocol:      TCP
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap-env
            - secretRef:
                name: {{ .Chart.Name }}-secret-env
