apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}-pod-console
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/component:  console
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  containers:
    - name: console
      image: {{ .Values.pod.app.image }}
      imagePullPolicy: Always
      command:
        - pause
      resources:
        requests:
          memory: {{ .Values.pod.app.resources.memory }}
        limits:
          memory: {{ .Values.pod.app.resources.memory }}
      envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-configmap-env
        - secretRef:
            name: {{ .Chart.Name }}-secret-env
