apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret-tls
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
type: kubernetes.io/tls
data:
  tls.crt: {{ printf "%s/%s/%s" "tls" .Release.Namespace "tls.crt" | .Files.Get | b64enc }}
  tls.key: {{ printf "%s/%s/%s" "tls" .Release.Namespace "tls.key" | .Files.Get | b64enc }}
