apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      env: production
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        env: production
    spec:
      containers:
        - name: mysql
          image: mysql:5.7.24
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            tcpSocket:
              port: 3306
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command:
                - sh
                - -c
                - "MYSQL_PWD=\"$MYSQL_PASSWORD\" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: mysql-configmap
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
              protocol:      TCP
              name:          mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name:      mysql-volume
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-volume-claim
