{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name:     {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name:     {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.deployment.redis.image }}
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.deployment.redis.port }}
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command:
                - redis-cli
                - ping
          resources:
            requests:
              memory: {{ .Values.deployment.redis.resources.memory }}
            limits:
              memory: {{ .Values.deployment.redis.resources.memory }}
          ports:
            - containerPort: {{ .Values.deployment.redis.port }}
              protocol:      TCP
              name:          redis
          volumeMounts:
            - mountPath: /data
              name:      redis-volume
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-persistent-volume-claim
{{- end }}
