{{- if .Values.deployment.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-persistent-volume-claim
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistent_volume_claim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistent_volume_claim.storage }}
{{- end }}
