apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app.kubernetes.io/name:       {{ .Chart.Name }}
    app.kubernetes.io/instance:   {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:                {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if .Values.service.externalName }}
  externalName: {{ .Values.service.externalName }}
  {{- else }}
  ports:
    - port:       {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol:   TCP
  selector:
    app.kubernetes.io/name:     {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- end }}
